### ISSUE TITLE
请问对中文效果怎么样 ，是否能提供相应demo

### ISSUE THREAD

**Issue by yulj21** [bytedance/LatentSync#1]

**Comment by chunyu-li** [comment]
我随便找了段中文音频用 demo 第二个视频跑了一下，有一定 sync 效果但不算好。
主要是我们的数据集中大部分都是英文视频，中文视频基本没有，对于中文的 sync 效果基本上只能靠：

1. 多语言版本的 whisper encoder
2. Diffusion models 的泛化性

https://github.com/user-attachments/assets/de9a9896-aadb-4035-83a6-710e140bbd8e

欢迎贴一些 case 来帮助我们发现模型的缺陷

**Comment by yulj21** [comment]
https://github.com/user-attachments/assets/409f0b88-bf77-4e45-9537-07eb226fe3a4

这个是我跑的结果，感觉中文差点意思，后续是否有支持中文的版本

> 我随便找了段中文音频用 demo 第二个视频跑了一下，有一定 sync 效果但不算好。 主要是我们的数据集中大部分都是英文视频，中文视频基本没有，对于中文的 sync 效果基本上只能靠：
> 
> 1. 多语言版本的 whisper encoder
> 2. Diffusion models 的泛化性
> 
>  chinese.mp4 
> 欢迎贴一些 case 来帮助我们发现模型的缺陷

**Comment by chunyu-li** [comment]
短期内应该没时间训一个新版本的了，不过我们已经 release 了训练代码，你可以自己训一下，多加一些中文数据应该就可以了

**Comment by chunyu-li** [comment]
> 试了下，中文的嘴型有点差

我新加了 Classifier-Free Guidance 的功能，你可以调一下这个参数看看能不能让嘴形生成的更好一点。

**Comment by ashwani-ver** [comment]
@chunyu-li if we use whisper model finetuned on chinese dataset.. will it improve the lipsync?
Thank You.
