### ISSUE TITLE
Train second-stage error 

### ISSUE THREAD

**Issue by SzhangS** [bytedance/LatentSync#5]
How yo solve this?
ValueError: Incompatible shapes for attention inputs:
  query.shape: torch.Size([40, 1024, 1, 40])
  key.shape  : torch.Size([128, 50, 1, 40])
  value.shape: torch.Size([128, 50, 1, 40])
HINT: We don't support broadcasting, please use `expand` yourself before calling `memory_efficient_attention` if you need to
Steps:   0%|                                                                                                                        | 0/10000000 [00:15<?, ?it/s]
[2024-12-25 11:20:11,450] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 105427) of binary: /workspace/env/latentsync/bin/python

 my second-stage.yaml is :
data:
  syncnet_config_path: configs/syncnet/syncnet_16_pixel.yaml
  train_output_dir: debug/unet
  train_fileslist: ""
  train_data_dir: "./fine_tune/memo_in/"
  audio_cache_dir: "./temp_aud_cache"

  val_video_path: assets/demo1_video.mp4
  val_audio_path: assets/demo1_audio.wav
  batch_size: 1 # 8
  num_workers: 1 # 11
  num_frames: 5
  resolution: 256
  mask: fix_mask
  audio_sample_rate: 16000
  video_fps: 25

ckpt:
  resume_ckpt_path: checkpoints/latentsync_unet.pt
  save_ckpt_steps: 5000

run:
  pixel_space_supervise: true
  use_syncnet: true
  sync_loss_weight: 0.05 # 1/283
  perceptual_loss_weight: 0.1 # 0.1
  recon_loss_weight: 1 # 1
  guidance_scale: 1.0 # 1.5 or 1.0
  trepa_loss_weight: 10
  inference_steps: 20
  seed: 1247
  use_mixed_noise: true
  mixed_noise_alpha: 1 # 1
  mixed_precision_training: true
  enable_gradient_checkpointing: false
  enable_xformers_memory_efficient_attention: true
  max_train_steps: 10000000
  max_train_epochs: -1

optimizer:
  lr: 1e-5
  scale_lr: false
  max_grad_norm: 1.0
  lr_scheduler: constant
  lr_warmup_steps: 0

model:
  act_fn: silu
  add_audio_layer: true
  custom_audio_layer: false
  audio_condition_method: cross_attn # Choose between [cross_attn, group_norm]
  attention_head_dim: 8
  block_out_channels: [320, 640, 1280, 1280]
  center_input_sample: false
  cross_attention_dim: 384
  down_block_types:
    [
      "CrossAttnDownBlock3D",
      "CrossAttnDownBlock3D",
      "CrossAttnDownBlock3D",
      "DownBlock3D",
    ]
  mid_block_type: UNetMidBlock3DCrossAttn
  up_block_types:
    [
      "UpBlock3D",
      "CrossAttnUpBlock3D",
      "CrossAttnUpBlock3D",
      "CrossAttnUpBlock3D",
    ]
  downsample_padding: 1
  flip_sin_to_cos: true
  freq_shift: 0
  in_channels: 13 # 49
  layers_per_block: 2
  mid_block_scale_factor: 1
  norm_eps: 1e-5
  norm_num_groups: 32
  out_channels: 4 # 16
  sample_size: 64
  resnet_time_scale_shift: default # Choose between [default, scale_shift]
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false

  # Actually we don't use the motion module in the final version of LatentSync
  # When we started the project, we used the codebase of AnimateDiff and tried motion module
  # But the results are poor, and we decied to leave the code here for possible future usage
  use_motion_module: false
  motion_module_resolutions: [1, 2, 4, 8]
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
      - Temporal_Self
      - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 16
    temporal_attention_dim_div: 1
    zero_initialize: true

**Comment by chunyu-li** [comment]
change `num_frames` from 5 to 16 will solve the problem, actually our code currently does not support 5 frames input

**Comment by chunyu-li** [comment]
I fixed bug of loading wrong num_frames in Whisper encoder, see commit https://github.com/bytedance/LatentSync/commit/3954a39eef1c988b4f93eb0e0b6a0b948c99e6f3. Now this error will not apear, but still note that if you want to train U-Net with 5 frames, you need to first train a 5 frames SyncNet, our released SyncNet is for 16 frames input. By the way, the VideoMAE cannot be used since its input frames are 16.

**Comment by SzhangS** [comment]
Thanks very much.

**Comment by T2-MI** [comment]
Can you tell me the GPU setting about train， thank you
