### ISSUE TITLE
数据预处理问题

### ISSUE THREAD

**Issue by fenghe12** [bytedance/LatentSync#6]
数据预处理后（使用hdtf测试），似乎有一些数据是静止不动的（affine_transformed）

**Comment by fenghe12** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/pfs-mc0p4k/cvg/team/didonglin/fh/l/HDTF/HDTF_split/av_synced_3'

**Comment by chunyu-li** [comment]
静止不动的是指画面静止吗，那只能是因为你原视频里就有一些片段是静止的。

**Comment by fenghe12** [comment]
okok 我拿其他的数据测试一下吧 感谢及时回复

**Comment by wvinzh** [comment]
请问，有完整版的HDTF数据集吗，方便共享吗
 @chunyu-li @fenghe12

**Comment by fenghe12** [comment]
我有一部分，你还需要么
