### ISSUE TITLE
Result frames are pixelated

### ISSUE THREAD

**Issue by opetliak** [bytedance/LatentSync#7]
Hi, when I run inference.sh, the resulting frames are pixelated.
![download - 2024-12-30T174505 809](https://github.com/user-attachments/assets/6a390506-57d0-4d13-81b9-16c030803e4a)
Let me know if you’d like me to add more details or context!

**Comment by chunyu-li** [comment]
What's your `ffmpeg` version?

**Comment by endofD** [comment]
is that because of vae decode and encode  loss issue?
